x1= int(input("Enter x1: "))
y1=int (input("Enter y1: "))
x2=int (input("Enter x2: "))
y2=int (input("Enter y2: "))
val=((x2-x1)**2)+((y2-y1)**2)
distance=round(val**(1/2),2)
print(f"The distance between the two points: {distance}")
